### ISSUE TITLE
Remove hard-coded constants and create mock endpoints

### ISSUE THREAD

**Issue by kimobrian** [AndelaOSP/wire#36]
## Constants

The URL's in the actions files need refactoring to avoid the hard coding.

Let's have a folder called `constants` and inside a file called `apiConstants.js` which should look like:

```javascript
var DEV_ENV = process.env.ENVIRONMENT;
let API_URL;
const isDev = DEV_ENV === 'DEV' ;
const isStaging = DEV_ENV === 'STAGING' ;
const isProd = DEV_ENV === 'PROD' ;

if(isDev) {
   API_URL = 'api';  // or `${window.location.protocol}//${window.location.host}/api`
} else if(isStaging) {
   API_URL = 'staging endpoint';
} else if(isProd) {
  API_URL = 'production endpoint';
}

const apiConstants = {
  API_URL,
  INCIDENTS: `${API_URL}/incidents/`,
  USERS: `${API_URL}/...`,
  NOTES: `...`
};

export default apiConstants;
```
then we can import and replace [such lines](https://github.com/AndelaOSP/wire/blob/65daada3742ea1308f530f2c34776650986116ac/src/actions/noteAction.jsx#L5) with the constants depending on whether we are fetching incidents or users or .... 
Let's use the same trend anywhere we are such constants.

## Mock Endpoints

With the above configuration, we can know where requests will be made to(dev/mock, prod or staging) depending on the environment.

To allow for front end `devs` to continue working without the backend, let's also have a 'mock_endpoints folder'

### Sample

`mock_endpoints/incidents.js`

```js
 incidents = {
   //an object with dummy incidents
}
let update = function() { // Update record in array using provided ID}
let delete = function() {}
let create = function() {}
let get = function() {}
let retrieve = function() {}

module.exports = {
  update,
  delete,
  create,
  get, // Get by ID
  retrieve // All incidents
}
```
To reduce your work, I will implement the methods. You guys setup the dummy data like 15 records each.

`mock_endpoints/mockIncidentMiddleware.js`

```js
const { update, delete, create, get, retrieve } = require('./incidents');
module.exports = function getIncident(req, res) {
    // delay response a bit to simulate an async operation
    setTimeout(
      () => {
        let incident = get(req.param.id);
        return res.json({ values: incident });
      },
      3000
    );
  });
};
...
```

Then inside `server.js`, we can have:

```js
const mockIncidentMiddleware = require('./mock_endpoints/mockIncidentMiddleware');
app.use(express.static(__dirname + './dist'));

app.get('api/incident/:id', mockIncidentMiddleware.get);

```

Make sure to have this on PT and suggestions are welcome, I'm not the final say.

**Comment by NaiRobley** [comment]
On it
